version: '3.8'

services:
    flask-app:
        container_name: flask-app
        build: app
        restart: always
        ports:
            - '5000:5000'
        volumes:
            - ./app:/app
        networks:
            - backend

    mysqlcontainer:
        container_name: mysqlcontainer
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: my_password
            MYSQL_DATABASE: Veterinarian
        ports:
            - '3308:3306'
        volumes:
            - ./database:/var/lib/mysql
        networks:
            - backend

networks:
    backend:

volumes:
    app:
    database:
